# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f05204e738e06884ad3b7dfa8b9fb3b916bc69374792710b38cc17e9078c6a0a2aa5f8be5d7590f4844b5537a1975c44a79e89161869fb33ef2524b8056ff1c

test:
  secret_key_base: 1f782ce208d220f70665985a8e3d8c3e7926af2290bc4bcd6b22d9ac45a02d3d3e029d296cee0c52b5c118669b4fe5e17df79832ee93130011bfd436b88af2e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
